### ISSUE TITLE
refresh token creating for new users without checking the signed in box

### ISSUE THREAD

**Issue by AnkitExcelerate** [Globalshala/Eval-Bridge-bugs#36] opened 2024-03-08 09:58 UTC

**Comment by NavnathGunjal7** [comment] 2024-03-18 17:24
@AnkitExcelerate please test if resolved close it

**Comment by Adnan-shariff** [comment] 2024-06-26 12:52
working as intended .
![2024-06-26 18_19_10-Window](https://github.com/Globalshala/Eval-Bridge-bugs/assets/168713554/ef0e7764-9456-4d2f-85c8-95c08a38800f)

**Closed by Adnan-shariff** 2024-06-26 12:52 UTC
Labels: changes done
