### ISSUE TITLE
Re -evaluation applications not able to send to next level

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#97] opened 2024-05-13 12:45 UTC
1. add one application for re-evaluation ==> it means it is already there in any one upload pool
2. and when it is assigned to new user and he is trying to send it to next level it's not happening getting error app id not found in rev pool

**Comment by Adnan-shariff** [comment] 2024-08-02 11:59
Facing same issue if we dont do any changes , but if we change CGPA value we are able to send to next level 
![2024-08-02 17_28_10-](https://github.com/user-attachments/assets/2854a4b5-2f42-4bf1-ae47-62f0d8f2ba12)

**Comment by MSGlobalShala** [comment] 2024-08-22 12:21
@Adnan-shariff  please verify, according to me it should be fixed

**Comment by Adnan-shariff** [comment] 2024-10-03 13:06
working as intended with production App#slu585250 , not yet tested on dev as on dev its not moving from Complete pool to upload pool.
![2024-10-03 18_32_07-Window](https://github.com/user-attachments/assets/de498f6f-24ca-4d10-af7c-c9ba3eb046d0)

**Closed** 2024-10-04 06:00 UTC
Labels: High Priority
