### ISSUE TITLE
user code is not changing if we are assign application to another user

### ISSUE THREAD

**Issue by NavnathGunjal7** [Globalshala/Eval-Bridge-bugs#179] opened 2024-06-14 12:51 UTC
1. application assign to user 1,
2. we assign application user 2
3. previous user code will be visible that is user 1 user code is visible

**Comment by NavnathGunjal7** [comment] 2024-06-14 12:53
@Adnan-shariff  / @AnkitExcelerate  please test this properly as we are showing correct user code on frontend and in db also correct user codes we are adding test all possible cases add your observations here in comment

**Comment by MSGlobalShala** [comment] 2024-08-07 04:40
@Adnan-shariff May I know the status of this bug

**Comment by Adnan-shariff** [comment] 2024-08-07 12:14
User code is changed if Evaluation  and Reviewer are different in both Frontend and db
![2024-08-07 17_41_31-Window](https://github.com/user-attachments/assets/0ae8fcea-5205-4193-909c-8470e8b1a159)
![2024-08-07 17_41_24-Window](https://github.com/user-attachments/assets/96d3ceaa-9552-4e38-ae59-571fd35fae01)
![2024-08-07 17_41_04-Window](https://github.com/user-attachments/assets/a16ff474-bcd1-4923-ab1a-ab17416fffec)
![2024-08-07 17_36_15-Window](https://github.com/user-attachments/assets/1b74970d-a353-4dc2-bd09-fdc5a7ca0ff6)

**Comment by Adnan-shariff** [comment] 2024-08-08 06:26
Hi @MSGlobalShala  when the evaluator and Reviewer are same so the user code is also same hence we are not facing any issue 
![2024-08-08 11_21_38-Mail](https://github.com/user-attachments/assets/988c5673-32c4-410e-b52c-89d1ef75beb9)
![2024-08-08 11_20_59-Mail](https://github.com/user-attachments/assets/a510592f-43a4-4a2b-9b41-b77ed829ef89)

**Comment by Adnan-shariff** [comment] 2024-08-08 10:02
working as intended hence closing this issue.

**Closed by Adnan-shariff** 2024-08-08 10:02 UTC
