### ISSUE TITLE
assign appid to specific user 

### ISSUE THREAD

**Issue by ipankajparihar** [Globalshala/Eval-Bridge-bugs#33] opened 2024-03-07 07:53 UTC
**Describe the bug**
After assigning the appids to a user most of the its throwing error like "appid in wrong pool or wrong status"

**To Reproduce**
1. Go to   home dashboard
2. Click on assign appid to specific user 
3. Select appid and email and org

**Expected behavior**
It should throw one error at a time but show two errors

![Screenshot from 2024-03-07 13-15-10](https://github.com/Globalshala/Eval-Bridge-bugs/assets/69728174/132a1966-5db6-45bd-b293-6df821c62937)

**Comment by shivanim11** [comment] 2024-06-20 14:18
Duplicate of 
#5

**Closed by shivanim11** 2024-06-20 14:18 UTC
Labels: bug, duplicate, changes done
